FROM ghcr.io/aikcoo/docker-pw-server-base:master
WORKDIR /var/www/html

RUN apt-get update && apt-get install -y openssh-server
RUN echo 'root:aikcoo.com' | chpasswd
RUN mkdir /var/run/sshd && \
    sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config && \
    sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
